var message1 = "Simple Addition \n \t5+3 ";
console.log(message1);
console.log(5 + 3);
var message2 = "Simple Substraction \n \t11-3 ";
console.log(message2);
console.log(11 - 3);
var message3 = "Simple Division \n \t16/2";
console.log(message3);
console.log(16 / 2);
var message4 = "Simple Multiplication\n\t 2*4";
console.log(message4);
console.log(2 * 4);
